# Copyright(c) Liang Yiyan, Pekin University, 2026. All rights reserved.
# If you have carefully read this project, 
# you may find that the image similarity comparison function only returns a list.
# This is not good news for us, because it is difficult to determine whether the function is working properly.
# Therefore, we designed this program to check the results.

import os
import json
import shutil

from FileProcess import LogMessage
from FileProcess import GetFileName

# The path of the JSON file generated by the image similarity comparison function
JSON_FILE = ""
# The path of the folder where the images will be organized according to the similarity groups
OUTPUT_DIR = ""

if not os.path.exists(JSON_FILE):
    LogMessage(f"JSON file {JSON_FILE} not found.", Type="ERROR")
    exit(1)
    
# Load the JSON file
with open(JSON_FILE, "r", encoding="utf-8") as f:
    SimilarList = json.load(f)

# We will construct a mapping relationship between an image and a group.
# It is similar to the principle of union-find algorithm.
# If two images belong to the same group, they are similar to each other.
Groups = []
ImageToGroup = {}

for Pair in SimilarList:
    ImageA = Pair['ImageInFolderA']
    ImageB = Pair['ImageInFolderB']

    # If both images are not in any group, create a new group for them
    if ImageA not in ImageToGroup and ImageB not in ImageToGroup:
        NewGroup = {ImageA, ImageB}
        Groups.append(NewGroup)
        ImageToGroup[ImageA] = NewGroup
        ImageToGroup[ImageB] = NewGroup

    # If one image is in a group and the other is not,
    # add the other image to the same group
    elif ImageA in ImageToGroup and ImageB not in ImageToGroup:
        Group = ImageToGroup[ImageA]
        Group.add(ImageB)
        ImageToGroup[ImageB] = Group
    elif ImageB in ImageToGroup and ImageA not in ImageToGroup:
        Group = ImageToGroup[ImageB]
        Group.add(ImageA)
        ImageToGroup[ImageA] = Group
    
    # If two images belong to different groups, merge these two groups
    elif ImageToGroup[ImageA] is not ImageToGroup[ImageB]:
        GroupA = ImageToGroup[ImageA]
        GroupB = ImageToGroup[ImageB]

        # Merge GroupB into GroupA
        GroupA.update(GroupB)

        # Update the reference of all images in GroupB to GroupA
        for Image in GroupB:
            ImageToGroup[Image] = GroupA
        
        # Remove GroupB from Groups list
        Groups.remove(GroupB)

# Print the total number of groups of similar images found
print(f"Total {len(Groups)} groups of similar images found.")
LogMessage(f"Total {len(Groups)} groups of similar images found.", Type="INFO")

# To make sure that the folder is exist
if not os.path.exists(OUTPUT_DIR):
    os.makedirs(OUTPUT_DIR)

# For each group of similar images,
# we will create a subfolder in the output directory named "Group(i)"
# and copy all images in this group to the subfolder.
for IDx, Group in enumerate(Groups, 1):
    # Create a subfolder for the group
    GroupFolder = os.path.join(OUTPUT_DIR, f"Group{IDx:04d}")
    if not os.path.exists(GroupFolder):
        os.makedirs(GroupFolder)

    # =============== DEBUG ===============
    print(f"\nProcessing Group {IDx}/{len(Groups)} ({len(Group)} images)")

    CopiedImages = 0
    MissingImages = 0

    for ImagePath in Group:
        if os.path.exists(ImagePath):
            # Obtain the file name from the image path
            # Or you can use pathlib to get the file name. The usage is as follows:
            # ImageName = Path(ImagePath).name
            ImageName = GetFileName(ImagePath)
            # Construct the destination path for the image in the group folder
            Destination = os.path.join(GroupFolder, ImageName)

            # If the destination file already exists, skip copying to avoid overwriting
            if os.path.exists(Destination):
                continue

            # Copy the image to the group folder
            try:
                shutil.copy2(ImagePath, Destination)
                CopiedImages += 1
            except Exception as e:
                LogMessage(f"Error copying image: {ImagePath} to {Destination}. Error: {str(e)}", Type="ERROR")
                MissingImages += 1
        
        # If we could not find the image file,
        # we will log a warning message and count the number of missing images.
        else:
            LogMessage(f"Image file not found: {ImagePath}", Type="WARNING")
            MissingImages += 1

    # Print the number of images successfully copied and the number of missing images for this group
    print(f"  Successfully copied: {CopiedImages} images, Missing: {MissingImages} images")
