# Copyright(c) Liang Yiyan, Pekin University, 2026. All rights reserved.

# If you have carefully read this project, 
# you may find that the image similarity comparison function only returns a list.
# This is not good news for us, because it is difficult to determine whether the function is working properly.
# Therefore, we designed this program to check the results.

import os
import json
import shutil

import numpy as np
import matplotlib.pyplot as plt

from matplotlib.widgets import Button

from FileProcess import LogMessage
from FileProcess import GetFileName

# Disable Matplotlib default "save figure" shortcut (key "s") to avoid conflict with our custom Skip shortcut.
plt.rcParams['keymap.save'] = []

# The path of the JSON file generated by the image similarity comparison function
JSON_FILE = ""
# The path of the folder where the images will be organized according to the similarity groups
OUTPUT_DIR = ""
# The path of the JSON file used to store the review results of all the groups
RESULTS_FILE = ""
# The path of the folder where the kept images after review will be moved to
KEPT_DIR = ""

# Constant Definition
IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".bmp", ".tiff", ".tif", ".gif", ".webp"}

# Display mode
IMAGE_DISPLAY_MODE = "fit"
# Whether to show file names above each image
SHOW_FILE_NAMES = True

if not os.path.exists(JSON_FILE):
    LogMessage(f"JSON file {JSON_FILE} not found.", Type="ERROR")
    exit(1)
    
# Load the JSON file
with open(JSON_FILE, "r", encoding="utf-8") as f:
    SimilarList = json.load(f)

# We will construct a mapping relationship between an image and a group.
# It is similar to the principle of union-find algorithm.
# If two images belong to the same group, they are similar to each other.
Groups = []
ImageToGroup = {}

for Pair in SimilarList:
    ImageA = Pair['ImageInFolderA']
    ImageB = Pair['ImageInFolderB']

    # If both images are not in any group, create a new group for them
    if ImageA not in ImageToGroup and ImageB not in ImageToGroup:
        NewGroup = {ImageA, ImageB}
        Groups.append(NewGroup)
        ImageToGroup[ImageA] = NewGroup
        ImageToGroup[ImageB] = NewGroup

    # If one image is in a group and the other is not,
    # add the other image to the same group
    elif ImageA in ImageToGroup and ImageB not in ImageToGroup:
        Group = ImageToGroup[ImageA]
        Group.add(ImageB)
        ImageToGroup[ImageB] = Group
    elif ImageB in ImageToGroup and ImageA not in ImageToGroup:
        Group = ImageToGroup[ImageB]
        Group.add(ImageA)
        ImageToGroup[ImageA] = Group
    
    # If two images belong to different groups, merge these two groups
    elif ImageToGroup[ImageA] is not ImageToGroup[ImageB]:
        GroupA = ImageToGroup[ImageA]
        GroupB = ImageToGroup[ImageB]

        # Merge GroupB into GroupA
        GroupA.update(GroupB)

        # Update the reference of all images in GroupB to GroupA
        for Image in GroupB:
            ImageToGroup[Image] = GroupA
        
        # Remove GroupB from Groups list
        Groups.remove(GroupB)

# Print the total number of groups of similar images found
print(f"Total {len(Groups)} groups of similar images found.")
LogMessage(f"Total {len(Groups)} groups of similar images found.", Type="INFO")

# To make sure that the folder is exist
if not os.path.exists(OUTPUT_DIR):
    os.makedirs(OUTPUT_DIR)

# For each group of similar images,
# we will create a subfolder in the output directory named "Group(i)"
# and copy all images in this group to the subfolder.
for IDx, Group in enumerate(Groups, 1):
    # Create a subfolder for the group
    GroupFolder = os.path.join(OUTPUT_DIR, f"Group{IDx:04d}")
    if not os.path.exists(GroupFolder):
        os.makedirs(GroupFolder)

    # =============== DEBUG ===============
    print(f"\nProcessing Group {IDx}/{len(Groups)} ({len(Group)} images)")

    CopiedImages = 0
    MissingImages = 0

    for ImagePath in Group:
        if os.path.exists(ImagePath):
            # Obtain the file name from the image path
            # Or you can use pathlib to get the file name. The usage is as follows:
            # ImageName = Path(ImagePath).name
            ImageName = GetFileName(ImagePath)
            # Construct the destination path for the image in the group folder
            Destination = os.path.join(GroupFolder, ImageName)

            # If the destination file already exists, skip copying to avoid overwriting
            if os.path.exists(Destination):
                continue

            # Copy the image to the group folder
            try:
                shutil.copy2(ImagePath, Destination)
                CopiedImages += 1
            except Exception as e:
                LogMessage(f"Error copying image: {ImagePath} to {Destination}. Error: {str(e)}", Type="ERROR")
                MissingImages += 1
        
        # If we could not find the image file,
        # we will log a warning message and count the number of missing images.
        else:
            LogMessage(f"Image file not found: {ImagePath}", Type="WARNING")
            MissingImages += 1

    # Print the number of images successfully copied and the number of missing images for this group
    print(f"  Successfully copied: {CopiedImages} images, Missing: {MissingImages} images")

# The operation above just need to be performed once in most cases.
# Next, you may want to browse through all the similar groups, 
# and check whether the images in each group are indeed similar to each other.
# You may need to repeat this step multiple times, 
# that means you can consider to delete the preceding code.
ReviewResults = []

# Check whether the results file already exists.
# If it exists, we will load the results to avoid reviewing the same group multiple times.
if os.path.exists(RESULTS_FILE):
    with open(RESULTS_FILE, "r", encoding="utf-8") as f:
        ReviewResults = json.load(f)
LogMessage(f"Loaded existing review results for {len(ReviewResults)} groups.", Type="INFO")

# ReviewResults is a list of dict: {"Group": "...", "Kept": [...], "Dropped": [...]}
# We will build a set of already reviewed group names for quick lookup.
ReviewedGroups = {
    Item.get("Group")
    for Item in ReviewResults
    if isinstance(Item, dict) and Item.get("Group")
}

# Obtain the folder names of all groups in the output directory
GroupFolders = [
    f for f in os.listdir(OUTPUT_DIR) 
    if os.path.isdir(os.path.join(OUTPUT_DIR, f)) and f.startswith("Group")
]
# You can sort the group folders by their names to ensure a consistent review order here.
GroupFolders.sort()
# Or you can shuffle the group folders randomly to avoid any bias in the review order. 
# The usage of random shuffle is as follows:
# import random
# random.shuffle(GroupFolders)

# Record the index of the current group being reviewed.
CurrentGroupIndex = 0

# Create Figure and persistent buttons once; reuse them across all groups.
Figure = plt.figure(figsize=(14, 12))

ButtonAxesConfirm = Figure.add_axes([0.10, 0.02, 0.18, 0.05])
ButtonAxesAll     = Figure.add_axes([0.31, 0.02, 0.18, 0.05])
ButtonAxesNone    = Figure.add_axes([0.52, 0.02, 0.18, 0.05])
ButtonAxesSkip    = Figure.add_axes([0.73, 0.02, 0.18, 0.05])

ButtonConfirm = Button(ButtonAxesConfirm, "Confirm (Enter)", color="lightgreen")
ButtonAll     = Button(ButtonAxesAll,     "Select All (A)",  color="lightyellow")
ButtonNone    = Button(ButtonAxesNone,    "Select None (N)", color="lightyellow")
ButtonSkip    = Button(ButtonAxesSkip,    "Skip (S)",        color="lightgray")

# Track button axes so clf() replacements can leave them untouched.
ButtonAxesSet  = {
    ButtonAxesConfirm, 
    ButtonAxesAll, 
    ButtonAxesNone, 
    ButtonAxesSkip
}
# Track per-button on_clicked cids so we can disconnect before reconnecting.
PrevButtonCids = {
    ButtonConfirm: None, 
    ButtonAll:     None, 
    ButtonNone:    None, 
    ButtonSkip:    None
}
PrevCanvasConnections = []

while CurrentGroupIndex < len(GroupFolders):
    GroupFolder = GroupFolders[CurrentGroupIndex]

    # If the group has already been reviewed, skip it and move to the next group.
    if GroupFolder in ReviewedGroups:
        CurrentGroupIndex += 1
        continue
    
    # Otherwise, we need to get all images in the folder
    FolderPath = os.path.join(OUTPUT_DIR, GroupFolder)
    ImagePaths = [
        os.path.join(FolderPath, f) 
        for f in os.listdir(FolderPath) 
        if os.path.isfile(os.path.join(FolderPath, f)) and 
            os.path.splitext(f)[1].lower() in IMAGE_EXTENSIONS
    ]

    # If the group contains less than two images, skip it.
    # Of course, this situation is unlikely to happen.
    if len(ImagePaths) < 2:
        LogMessage(f"Group {GroupFolder} contains less than 2 images, skipping review.", Type="WARNING")
        CurrentGroupIndex += 1
        continue

    ImagesNum = len(ImagePaths)

    # Estimate the average image aspect ratio (width / height) and choose a grid
    # that maximizes screen usage while preserving each image aspect ratio.
    ImageRatios = []
    for ImagePath in ImagePaths:
        try:
            Image = plt.imread(ImagePath)
            if hasattr(Image, "shape") and len(Image.shape) >= 2 and Image.shape[0] > 0:
                ImageRatios.append(Image.shape[1] / Image.shape[0])
        except Exception:
            continue
    AvgImageRatio = float(np.mean(ImageRatios)) if ImageRatios else 1.0

    # Initially, we assume that all similar images should be deleted.
    Selected = {ImagePath: False for ImagePath in ImagePaths}

    # Disconnect old canvas event handlers from the previous group, then reuse the window.
    for Cid in PrevCanvasConnections:
        try:
            Figure.canvas.mpl_disconnect(Cid)
        except Exception:
            pass
    PrevCanvasConnections = []

    if not plt.fignum_exists(Figure.number):
        Figure = plt.figure(figsize=(14, 12))
    else:
        # Remove only image axes. Button axes are persistent and must be preserved.
        for Ax in Figure.get_axes():
            if Ax not in ButtonAxesSet:
                Ax.remove()

    # Here we define a function to update the title of the window.
    # This title will help you keep track of the review progress and some relevant statistics.
    # The function will be called a lot of times, so we define it separately to avoid code repetition.
    def MakeTitle():
        SelectedNum = sum(Selected.values())
        Figure.suptitle(
            f"Group {CurrentGroupIndex + 1}/{len(GroupFolders)} - {SelectedNum}/{ImagesNum} images selected",
            fontsize = 16, fontweight = "bold"
        )

    MakeTitle()

    # Display all images in a grid layout.
    # Show window first, then use the actual window size for layout.
    plt.show(block=False)
    # Allow the window to be rendered
    plt.pause(0.1)  

    # Use real figure pixel size instead of assuming a fullscreen/screen ratio.
    CanvasW, CanvasH = Figure.canvas.get_width_height()
    ViewRatio = (CanvasW / CanvasH) if CanvasH > 0 else (16 / 9)

    # Try different grid layouts and choose the one with the best score.
    BestScore = -1.0
    BestCols = 1
    BestRows = ImagesNum
    for TestCols in range(1, ImagesNum + 1):
        TestRows = int(np.ceil(ImagesNum / TestCols))
        CellW = ViewRatio / TestCols
        CellH = 1.0 / TestRows
        # "fit" scaling (no crop): scale image to fit in cell
        Scale = min(CellW / AvgImageRatio, CellH)
        UsedAreaPerCell = AvgImageRatio * (Scale ** 2)
        Coverage = (UsedAreaPerCell * ImagesNum) / ViewRatio
        EmptySlots = (TestRows * TestCols - ImagesNum)
        Score = Coverage - EmptySlots * 0.01
        if Score > BestScore:
            BestScore = Score
            BestCols = TestCols
            BestRows = TestRows

    Cols = BestCols
    Rows = BestRows

    # Reserve extra vertical spacing when file names are shown.
    if SHOW_FILE_NAMES:
        GridHSpace = 0.16
        GridTop = 0.90
    else:
        GridHSpace = 0.02
        GridTop = 0.92

    # Create a GridSpec for the image grid layout. 
    # We will use this GridSpec to place the images in the correct positions.
    GridSpec = Figure.add_gridspec(
        Rows, Cols, hspace = GridHSpace, wspace = 0.02,
        top = GridTop, bottom = 0.1, left = 0.01, right = 0.99
    )

    # Store the axes of all images in the group.
    AxesList = []

    # When the user clicks on an image, we need to toggle the selection state of this image,
    # and update the border color and the title of the window accordingly.
    def RefreshBorders():
        for IDx, ImagePath in enumerate(ImagePaths):
            Axes = AxesList[IDx]
            # If the image is selected to be kept, we will set the border color to mediumseagreen.
            # Otherwise we will set it to pink.
            Color = "mediumseagreen" if Selected[ImagePath] else "pink"
            # Draw the border arround the image.
            for Spine in Axes.spines.values():
                Spine.set_edgecolor(Color)
                Spine.set_linewidth(3)
                Spine.set_visible(True)
        # Update the title to reflect the current selection status.
        MakeTitle()
        Figure.canvas.draw_idle()

    # Display all images in the group and set up the click event for each image.
    for IDx, ImagePath in enumerate(ImagePaths):
        # Calculate the position of the image in the grid layout.
        Row = IDx // Cols
        Col = IDx % Cols

        Axes = Figure.add_subplot(GridSpec[Row, Col])
        AxesList.append(Axes)

        # Load the image and display it in the corresponding axes.
        try:
            Image = plt.imread(ImagePath)
            Axes.imshow(Image, aspect="equal")
        except Exception as e:
            LogMessage(f"Error loading image: {ImagePath}. Error: {str(e)}", Type="ERROR")
            Axes.text(0.5, 0.5, "Error loading image", fontsize=10, ha='center', va='center')

        # Show the file name of each image if needed
        if SHOW_FILE_NAMES:
            Axes.set_title(os.path.basename(ImagePath), fontsize=8, wrap=True, pad=6)
        
        # Keep frame visible for selection borders, hide only ticks.
        Axes.set_frame_on(True)
        Axes.set_xticks([])
        Axes.set_yticks([])

        # Define the click event for each image.
        def OnClick(Path, Axes):
            # When user clicks on an image, toggle the selection state of this image.
            def ToggleSelection(Event):
                if Event.inaxes == Axes:
                    Selected[Path] = not Selected[Path]
                    RefreshBorders()
            return ToggleSelection
        
        # Bind the click event to the corresponding axes of the image.
        PrevCanvasConnections.append(Figure.canvas.mpl_connect('button_press_event', OnClick(ImagePath, Axes)))

    # Initialize the borders of all images
    RefreshBorders()

    # Hide the position without images
    for IDx in range(ImagesNum, Rows * Cols):
        Row = IDx // Cols
        Col = IDx % Cols
        
        Axes = Figure.add_subplot(GridSpec[Row, Col])
        Axes.axis("off")

    # After images are filled, force a redraw with final geometry.
    Figure.canvas.draw()
    Figure.canvas.flush_events()

    # When the window is resized, we need to redraw the borders to ensure that 
    # they are always visible and correctly positioned.
    def OnResize(Event):
        Figure.canvas.draw_idle()
    PrevCanvasConnections.append(Figure.canvas.mpl_connect("resize_event", OnResize))

    # Unified action state machine for all close paths: None / Confirm / Skip / Quit
    Action = {"Type": None}
    
    def OnFigureClose(Event):
        if Action["Type"] is None:
            Action["Type"] = "Quit"
    PrevCanvasConnections.append(Figure.canvas.mpl_connect("close_event", OnFigureClose))

    # --------------- Define the button events ---------------

    # When user clicks the confirm button, 
    # we will save the review result of this group and move to the next group.
    def OnConfirm(Event):
        Action["Type"] = "Confirm"

        Kept = [Path for Path in ImagePaths if Selected[Path]]
        Dropped = [Path for Path in ImagePaths if not Selected[Path]]
        
        # Save the review result of this group to the results list and write the results to the results file.
        ReviewResults.append({
            "Group": GroupFolder,
            "Kept": Kept,
            "Dropped": Dropped
        })
        ReviewedGroups.add(GroupFolder)
        with open(RESULTS_FILE, "w", encoding="utf-8") as f:
            json.dump(ReviewResults, f, indent=4)

    # When user clicks the select all or none button, 
    # we will select or deselect all images in the current group, and update the borders and the title accordingly.
    def OnAll(Event):
        for Path in ImagePaths:
            Selected[Path] = True
        RefreshBorders()
    def OnNone(Event):
        for Path in ImagePaths:
            Selected[Path] = False
        RefreshBorders() 

    # When user clicks the skip button, we will just move to the next group.
    def OnSkip(Event):
        Action["Type"] = "Skip"

    # --------------- End of button events definition ---------------

    # We will also bind some keyboard shortcuts for the buttons to improve the efficiency of the review process.
    def OnKey(Event):
        if Event.key in ('enter', 'return'):
            OnConfirm(Event)
        elif Event.key in ('a', 'A'):
            OnAll(Event)
        elif Event.key in ('n', 'N'):
            OnNone(Event)
        elif Event.key in ('s', 'S'):
            OnSkip(Event)
        # We also provide a shortcut for quitting the review process and saving the results.
        elif Event.key in ('q', 'Q'):  
            Action["Type"] = "Quit"          
            with open(RESULTS_FILE, "w", encoding="utf-8") as f:
                json.dump(ReviewResults, f, indent=4)
            plt.close(Figure)

    # Disconnect previous button callbacks, then bind the new ones for this group.
    for Btn, Cid in PrevButtonCids.items():
        if Cid is not None:
            Btn.disconnect(Cid)
    PrevButtonCids[ButtonConfirm] = ButtonConfirm.on_clicked(OnConfirm)
    PrevButtonCids[ButtonAll]     = ButtonAll.on_clicked(OnAll)
    PrevButtonCids[ButtonNone]    = ButtonNone.on_clicked(OnNone)
    PrevButtonCids[ButtonSkip]    = ButtonSkip.on_clicked(OnSkip)

    PrevCanvasConnections.append(Figure.canvas.mpl_connect('key_press_event', OnKey))

    # Poll until the user confirms, skips, or closes the window manually.
    while Action["type"] is None:
        plt.pause(0.05)
        if not plt.fignum_exists(Figure.number):
            break

    # Single place to handle loop progression/exit after window closes.
    if Action["type"] == "quit":
        break
    CurrentGroupIndex += 1

# After reviewing all groups, we will move all kept images into a new folder
SuccessfullyMoved = 0

# Firstly, we need to ensure that all groups have been reviewed. 
# That means the number of review results is equal to the number of groups.
if len(ReviewResults) != len(GroupFolders):
    exit(1)
LogMessage(f"All groups reviewed. Total groups: {len(ReviewResults)}/{len(GroupFolders)}.", Type="INFO")

# Then we will create the kept images folder if it does not exist.
if not os.path.exists(KEPT_DIR):
    os.makedirs(KEPT_DIR)

# Move all kept images into the new folder. 
# Note that it is just a copy operation, the original images in the group folders will not be deleted.
# However, we will not keep the directory structure of the group folders.
# So please ensure that different images do not have the same file name with each other.
# Otherwise, we will only keep the first one we encounter and skip the rest to avoid overwriting.
for Result in ReviewResults:
    KeptImages = Result.get("Kept", [])
    for ImagePath in KeptImages:
        if os.path.exists(ImagePath):
            ImageName = os.path.basename(ImagePath)
            Destination = os.path.join(KEPT_DIR, ImageName)
            # If the destination file already exists, we will log a warning message and skip this image to avoid overwriting.
            if os.path.exists(Destination):
                LogMessage(f"File name conflict: {Destination} already exists. Skipping {ImagePath}.", Type="WARNING")
                continue
            # Copy the image to the kept images folder.
            try:
                shutil.copy2(ImagePath, Destination)
                SuccessfullyMoved += 1
            except Exception as e:
                LogMessage(f"Error copying image: {ImagePath} to {Destination}. Error: {str(e)}", Type="ERROR")

        else:
            LogMessage(f"Kept image file not found: {ImagePath}", Type="WARNING")

LogMessage(f"Kept images have been moved to: {KEPT_DIR}. Total successfully moved: {SuccessfullyMoved}.", Type="INFO")