# Copyright(c) Liang Yiyan, Pekin University, 2026. All rights reserved.

# This file contains some functions for post-processing similar images. 
# I have to note that these functions may not be highly versatile, 
# as they usually require a specific file name or scenario to function. 
# This is also why I have placed these functions in a folder.

import os
import json
import shutil

from FileProcess import LogMessage

# Imagine a scenario where you have two image sources: Source A and Source B.
# You want to find out how many pairs of similar images exists between these two sources.
# To distinguish the images from these two sources, 
# you have named the images with prefixes "SourceA-" and "SourceB-" respectively.
# In this case, you can use the following function to post-process the results of similar image detection.
def FilterDifferentSourcesPairs(InputFile: str, OutputFile: str, SourcePrefixes: list[str]) ->  list:
    # Read the result generated by the similar image detection tool.
    if not os.path.exists(InputFile):
        LogMessage(f"Input file not found: {InputFile}", Type="ERROR")
        return

    with open(InputFile, "r", encoding="utf-8") as f:
        SimilarPairs = json.load(f)
    LogMessage(f"Total similar pairs found: {len(SimilarPairs)}")

    FilteredPairs = []
    UnknownSourceCounts = 0

    for Record in SimilarPairs:
        ImageA = Record['ImageInFolderA']
        ImageB = Record['ImageInFolderB']

        # Obtain the base names of the images for prefix extraction
        BaseNameA = os.path.basename(ImageA)
        BaseNameB = os.path.basename(ImageB)

        # Extract the source prefixes from the image names
        SourceA = next((prefix for prefix in SourcePrefixes if BaseNameA.startswith(prefix)), None)
        SourceB = next((prefix for prefix in SourcePrefixes if BaseNameB.startswith(prefix)), None)

        # If either image does not belong to any of the specified sources, 
        # we will skip this pair and count it as an unknown source pair.
        if SourceA is None or SourceB is None:
            UnknownSourceCounts += 1
            continue

        # If the two images belong to different sources, we will keep this pair.
        if SourceA != SourceB:
            FilteredPairs.append(Record)

    LogMessage(f"Pairs with unknown sources: {UnknownSourceCounts}", Type="WARNING")
    LogMessage(f"Pairs from different sources: {len(FilteredPairs)}")

    # Save the filtered results to a new JSON file if the OutputFile parameter is provided.
    if OutputFile:
        with open(OutputFile, "w", encoding="utf-8") as f:
            json.dump(FilteredPairs, f, indent=4)
        LogMessage(f"Filtered pairs saved to: {OutputFile}")

    return FilteredPairs

# After completing the image similarity detection, 
# you may want to obtain all the images that do not have any similar counterparts.
# That means these images are unique in the dataset.
# The following function will extract all the unique images from the results of similar image detection.
def ExtractUniqueImages(SourceFolder: str, SimilarPairsFile: str, OutputDir: str) -> list:
    # Check if the source folder and the similar pairs file exist.
    if not os.path.exists(SourceFolder):
        LogMessage(f"Source folder not found: {SourceFolder}", Type="ERROR")
        return
    if not os.path.exists(SimilarPairsFile):
        LogMessage(f"Similar pairs file not found: {SimilarPairsFile}", Type="ERROR")
        return
    
    # Read the similar pairs from the JSON file.
    with open(SimilarPairsFile, "r", encoding="utf-8") as f:
        SimilarPairs = json.load(f)

    # Extract the names of images that appear in the similar pairs.
    SimilarImages = set()
    for Record in SimilarPairs:
        SimilarImages.add(os.path.basename(Record['ImageInFolderA']))
        SimilarImages.add(os.path.basename(Record['ImageInFolderB']))
    LogMessage(f"Total similar images found: {len(SimilarImages)}")

    # List all images in the source folder and identify those that are not in the similar images set.
    UniqueImages = []
    for ImageName in os.listdir(SourceFolder):
        if ImageName not in SimilarImages:
            UniqueImages.append(ImageName)
    LogMessage(f"Total unique images found: {len(UniqueImages)}")

    # If there are no unique images, it is unnecessary to create the output directory.
    if len(UniqueImages) == 0:
        return []    
    if not os.path.exists(OutputDir):
        os.makedirs(OutputDir)

    # Copy the unique images to the output directory.
    SuccessfulCopies = 0
    FailedCopies = 0

    for ImageName in UniqueImages:
        SourcePath = os.path.join(SourceFolder, ImageName)
        DestinationPath = os.path.join(OutputDir, ImageName)
        
        try:
            shutil.copy2(SourcePath, DestinationPath)
            SuccessfulCopies += 1
        except Exception as e:
            LogMessage(f"Failed to copy {SourcePath} to {DestinationPath}. Error: {str(e)}", Type="ERROR")
            FailedCopies += 1

    LogMessage(f"Successfully copied {SuccessfulCopies} unique images to: {OutputDir}")
    if FailedCopies > 0:
        LogMessage(f"Failed to copy {FailedCopies} unique images. Please check the log for details.", Type="WARNING")
    
    return UniqueImages

# Delete all images that start with a specific prefix in the given folder.
def DeleteImagesWithPrefix(FolderPath: str, Prefix: str) -> None:
    # Check if the source folder exists.
    if not os.path.exists(FolderPath):
        LogMessage(f"Folder not found: {FolderPath}", Type="ERROR")
        return
    
    # List all images in the folder and delete those that start with the specified prefix.
    DeleteCount = 0
    for ImageName in os.listdir(FolderPath):
        if ImageName.startswith(Prefix):
            ImagePath = os.path.join(FolderPath, ImageName)
            
            try:
                os.remove(ImagePath)
                DeleteCount += 1
            except Exception as e:
                LogMessage(f"Failed to delete {ImagePath}. Error: {str(e)}", Type="ERROR")

    LogMessage(f"Successfully deleted {DeleteCount} images with prefix '{Prefix}' from: {FolderPath}")
